### ISSUE TITLE
[Bug] - The addon will emit duplicate blacklist messages for guilds when new players join a raid group

### ISSUE THREAD

**Issue by dadams4** [Krught/beneblacklist#1]
**Issue**: When a player belonging to a blacklisted guild joins a raid group, the addon will emit duplicate blacklist messages for every subsequent player that joins the raid.
**Steps to reproduce**: 
- Create a raid group
- Invite a player from a blacklisted guild. Observe a message of the format "<'Guild Name'> is on the Classic Blacklist!" will be sent in raid chat by any users with the addon.
- Invite another player from a non-blacklisted guild. Observe a duplicate message from the previous step is also sent in chat. This will be repeated for any number of players that are invited to the group.

In silent mode, it will instead print duplicate messages that only the addon user sees.

**Workaround**: Enable silent mode when this happens

**Severity**: High, having to enable silent mode defeats the point of the addon. Having the chat spammed with duplicate messages can be annoying for other raid members.

**Comment by Krught** [comment]
New Update causes Guilds to not be spammed if multiple raid/party members from a blacklisted guild.
Also doesn't cause guilds to be re-announced if raid groups are moved around.

Should now work the same as players, aka only one initial post about the blacklisted guild, unless someone from the blacklisted guild is kicked; and then another from the same guild is re-invited then should message again.
